theme: minima
title: Install Radmc3d with WSL
description: My Main Site -- GehangMa.github.io
highlighter: rouge
markdown: kramdown
kramdown:
  input: GFM
copyright: >-
  &copy; #YEAR# èˆª
  [MIT License](https://opensource.org/license/mit/)
